/* Chapter 16 — The Season */
(function (FD) {
  const ALL = ['div', 'conf4', 'nfc4', 'place2', 'g17'];
  FD.CH.push({
    title: 'The Season', sub: 'Calendar, schedule formula, TV, playoffs, offseason',
    base: { cam: { x: 60, y: 26.67, w: 190 }, bug: {} },
    steps: [
      {
        title: 'Where the Patriots sit',
        bug: { reset: true, hide: true },
        cam: { x: 60, y: 26.67, w: 190 },
        players: [], routes: [], marks: [], zones: [], los: null, fd: null, ball: false,
        ov: [{ id: 'lg', type: 'league', pos: 'c', hl: 'AFC East' }],
        l3: { k: 'Quick reminder', t: 'AFC East', s: 'Bills · Dolphins · Patriots · Jets' },
        notes: {
          p: ['Before we zoom out to the whole season: remember where we live. AFC, East division, with Buffalo, Miami and the Jets.',
            'Almost everything about the schedule and the playoffs is built on this grid of 2 conferences and 8 divisions.',
            'Keep the AFC East in mind: it decides 6 of our 17 games and our easiest path to the playoffs.'],
          a: 'The division is your homeroom: the same classmates every year.',
          x: 'The 8×4 alignment has been fixed since 2002, which is what makes the rotating schedule formula possible.',
        },
      },
      {
        title: 'The football year',
        ov: [{ id: 'cal', type: 'calendar', pos: 'c', foot: 'The **2026 season** runs Sept 2026 → Feb 2027: a season is named by the year it **starts**' }],
        l3: null,
        notes: {
          p: ['A football year in one ribbon. March: free agency opens the new league year. April: the Draft. May–June: OTAs and minicamp.',
            'Late July: training camp. August: preseason, 3 exhibition games per team that don\'t count.',
            'September to early January: the regular season. 18 weeks, 17 games, 1 bye week per team. In 2026 it kicked off on September 9 with the Patriots at Seattle.',
            'Only 17 games: compare 82 in the NBA or 162 in baseball. One NFL game is worth about 10 baseball games.',
            'January: playoffs, 14 teams. February: the Super Bowl.',
            'Because it crosses New Year, a season is named for the year it starts. The 2025 season ended with Super Bowl LX in February 2026.'],
          a: 'Like a school year: "the 2026 school year" also finishes in 2027.',
          x: 'The 2026 Hall of Fame Game was Aug 7, then 3 preseason weekends (Aug 14–30). Week 18 is the weekend of Jan 9–10, 2027. Preseason dropped from 4 to 3 games in 2021 when the season grew to 17.',
        },
      },
      {
        title: 'Who we play: division',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'div', show: ['div'] }],
        l3: null,
        notes: {
          p: ['The 17 opponents aren\'t random. There\'s a fixed formula, the same for all 32 teams.',
            'Step 1: your 3 division rivals, twice each (once at home, once away). That\'s 6 games.',
            'So the Patriots see the Bills, Dolphins and Jets twice every single season.'],
          a: 'The division games are the family dinners: twice a year, no excuses.',
          x: 'Division record is also the 2nd tiebreaker for winning the division, so these 6 games count double in practice.',
        },
      },
      {
        title: '+4: another AFC division',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'conf4', show: ['div', 'conf4'] }],
        l3: null,
        notes: {
          p: ['Step 2: all 4 teams from one other AFC division. 2 at home, 2 away.',
            'It rotates every year, so over 3 seasons you play every AFC division.',
            'Running total: 6 + 4 = 10.'],
          a: 'Visiting a different neighborhood in your own city each year.',
          x: 'Intra-conference division pairings rotate on a 3-year cycle.',
        },
      },
      {
        title: '+4: an NFC division',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'nfc4', show: ['div', 'conf4', 'nfc4'] }],
        l3: null,
        notes: {
          p: ['Step 3: all 4 teams from one NFC division. 2 at home, 2 away.',
            'This rotates every 4 years. That\'s why some NFC teams visit Foxborough only once every 8 years or so.',
            'Running total: 14.'],
          a: 'The once-in-a-while trip to the other side of the country.',
          x: 'Inter-conference division pairings run on a 4-year cycle; the 17th game (below) adds one more NFC opponent.',
        },
      },
      {
        title: '+2: same-place AFC teams',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'place2', show: ['div', 'conf4', 'nfc4', 'place2'] }],
        l3: null,
        notes: {
          p: ['Step 4: two games against AFC teams that finished in the same place in their division last year.',
            'They come from the two AFC divisions not already on the schedule. A 1st-place team plays the other 1st-place teams, last plays last.',
            'This is how the league gives tougher schedules to good teams and easier ones to bad teams. Running total: 16.'],
          a: 'Like a tennis tournament that seeds the top players against each other.',
          x: 'This is the only part of the schedule based on performance; it\'s why "strength of schedule" varies team to team.',
        },
      },
      {
        title: '+1: the 17th game',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'g17', show: ALL }],
        l3: null,
        notes: {
          p: ['Step 5: one extra game against a same-place NFC team, from an NFC division not already on the schedule.',
            'This one was added in 2021 when the season went to 17 games.',
            '6 + 4 + 4 + 2 + 1 = 17.'],
          a: 'The bonus question at the end of the exam.',
          x: 'The 17th-game NFC division is determined by a separate rotation so it never duplicates the 4-game NFC pairing.',
        },
      },
      {
        title: 'Home and away',
        ov: [{ id: 'mx', type: 'matrix', pos: 'c', hl: 'all' }],
        tags: ['VERIFY: 2026 = NFC teams host 9 (AFC teams, incl. NE, host 8)'],
        l3: null,
        notes: {
          p: ['17 games is an odd number, so it can\'t split evenly: every team plays 8 or 9 home games.',
            'The extra home game alternates between the conferences each year: one year all AFC teams get 9 home games, the next year all NFC teams do.',
            'Plus: some home games are moved overseas as international games, so a team can "host" a game in London or Munich.',
            'That\'s the full formula: 17 opponents, known years in advance, only the dates and times are a surprise.'],
          a: 'Hosting the party 8 or 9 times; the 9th rotates between the two families.',
          x: 'The 17th game is the one that decides 8 vs 9; it has been played at the AFC site in odd years (2021, 2023, 2025), so 2026 should be an NFC-host year.',
        },
      },
      {
        title: 'When games are played & on TV',
        ov: [{ id: 'tv', type: 'tv', pos: 'c', t: 'Where to watch (US, 2026)', items: [
          { logo: 'tv_cbs', slot: 'Sunday 1:00 & 4:05/4:25 PM ET', sub: 'CBS · mostly AFC road teams' },
          { logo: 'tv_fox_sunday', slot: 'Sunday 1:00 & 4:05/4:25 PM ET', sub: 'FOX · mostly NFC road teams' },
          { logo: ['tv_nbc', 'tv_snf'], slot: 'Sunday Night Football', sub: 'NBC · 8:20 PM ET' },
          { logo: 'tv_espn', slot: 'Monday Night Football', sub: 'ESPN / ABC · 8:15 PM ET' },
          { logo: 'tv_prime', slot: 'Thursday Night Football', sub: 'Prime Video · 8:15 PM ET' },
          { txt: 'NETFLIX', slot: 'Special games', sub: 'e.g. Week 18 Saturday 1:00 PM ET' },
        ], foot: 'Late-season Saturdays also go to NFL Network (Wk 16) and NBC/Peacock (Wk 17)' }],
        tags: ['VERIFY: which networks carry the 2026 Christmas Day games'],
        l3: null,
        notes: {
          p: ['Sunday afternoon is the heart of it: games at 1:00 PM and a late window at 4:05 or 4:25 PM Eastern.',
            'Those go to CBS and FOX. Roughly: CBS shows games where the road team is from the AFC, FOX when it\'s from the NFC. So most Patriots road games are on CBS.',
            'Then the prime-time games, one game, whole country watching: Sunday Night on NBC, Monday Night on ESPN/ABC, Thursday Night streaming on Amazon Prime Video.',
            'Streaming is growing: Netflix has holiday and special games, including a Week 18 Saturday game this season.'],
          a: 'Sunday afternoon is the buffet; prime time is the one big dinner everyone sits down for.',
          x: 'What you see on Sunday afternoon depends on your market: CBS/FOX affiliates show the local team first. NFL Sunday Ticket (YouTube) is how out-of-market fans watch everything.',
        },
      },
      {
        title: 'Flex scheduling & the world',
        ov: [{ id: 'fx', type: 'compare', pos: 'c', cols: [
          { t: 'Flex scheduling', c: '#38bdf8', items: ['Good games get **moved into prime time**, dull ones out', 'SNF: up to 2× in Weeks 5–10, any week 11–17', 'MNF: Weeks 12–17 · TNF: up to 2× in Weeks 13–17', '**Week 18**: matchups & times set after Week 17'] },
          { t: '2026 international games: 9', c: '#facc15', items: ['**Melbourne** (first ever in Australia, Sept 10)', '**London** ×3 · **Paris** · **Madrid** · **Munich**', '**Rio de Janeiro** · **Mexico City**'] },
        ], foot: 'Source: NFL flexible scheduling procedures (2026) · NFL international games' }],
        tags: [],
        l3: null,
        notes: {
          p: ['The schedule comes out in spring, but prime time is not locked. If a game turns out to be a dud, the league can "flex" a better one into Sunday night.',
            'In 2026 flex applies to Sunday, Monday and Thursday nights in set windows. Fans get at least 12 days\' notice (6 days late in the year).',
            'Week 18 is special: the league waits until Week 17 is over, then puts the games with playoff stakes in the best slots.',
            'The NFL is also going global: 9 regular-season games abroad in 2026, starting with the first-ever game in Melbourne, Australia (49ers vs Rams).'],
          a: 'Flex scheduling is a TV station swapping in the hit show and moving the rerun to the afternoon.',
          x: 'Only Sunday-afternoon games can be flexed into a night slot; the displaced night game moves to Sunday afternoon. Flex began in 2006 with Sunday Night Football.',
        },
      },
      {
        title: 'Standings & tiebreakers',
        tags: [],
        ov: [{ id: 'st', type: 'panel', pos: 'c', k: 'Standings', t: 'Ranked by winning percentage', num: true, items: [
          '**Win %** (a tie counts as half a win, half a loss)',
          'Tied in the division? **Head-to-head** record',
          'Then **division** record',
          'Then record in **common games**',
          'Then **conference** record',
          '…then strength of victory, strength of schedule, points… and finally a **coin toss**',
        ], foot: 'Division tiebreak, two clubs · nfl.com tie-breaking procedures' }],
        l3: null,
        notes: {
          p: ['Standings are by winning percentage, not points. A tie game counts as half a win and half a loss.',
            'When two teams in the same division finish with the same record, the first tiebreaker is head-to-head: who won the games between them.',
            'Still tied: division record, then record against common opponents, then conference record.',
            'After that it gets nerdy: strength of victory, strength of schedule, point rankings… and the very last step is a coin toss.'],
          a: 'Like a sports-day medal tie: first look at who beat whom directly, then dig deeper.',
          x: 'Wild-card ties between teams from different divisions use a different order: head-to-head (if applicable), then conference record, then common games (minimum 4).',
        },
      },
      {
        title: 'Playoffs: 14 teams',
        ov: [{ id: 'br', type: 'bracket', pos: 'c', stage: 2, foot: '**#1 seed: bye** · Wild Card: 2v7 · 3v6 · 4v5 · then **reseed**: top seed left plays the lowest' }],
        l3: null,
        notes: {
          p: ['Seven teams per conference make the playoffs, 14 in total.',
            'The 4 division winners are seeded 1 to 4 by record. The 3 best other teams are the wild cards, seeded 5 to 7.',
            'Only the #1 seed gets a bye and skips the Wild Card round. The rest play: 2 vs 7, 3 vs 6, 4 vs 5.',
            'After each round the bracket is reseeded: the best remaining seed always plays the lowest remaining seed. And the higher seed hosts.',
            'Single elimination: lose once and your season is over.'],
          a: 'March Madness, but with only 14 teams and the top seed sleeping through round one.',
          x: 'A division winner is always seeded above every wild card, even with a worse record, so a 10-7 division winner hosts a 13-4 wild card.',
        },
      },
      {
        title: 'Conference title & the Super Bowl',
        ov: [{ id: 'br', type: 'bracket', pos: 'c', stage: 4, foot: 'Super Bowl: AFC champion vs NFC champion · **neutral site** · early February' }],
        l3: null,
        notes: {
          p: ['After the Divisional round, two teams remain in each conference. They play the Conference Championship: the winner is the AFC or NFC champion.',
            'The two champions meet in the Super Bowl, played at a neutral site chosen years in advance.',
            'The Patriots were AFC champions last season and reached Super Bowl LX, losing to Seattle.',
            'Winner gets the Lombardi Trophy. The Patriots have six.'],
          a: 'The World Cup final: the venue is picked long before anyone knows who\'ll be in it.',
          x: 'Playoff overtime differs from the regular season: 15-minute periods, both teams get a possession, and it continues until there\'s a winner (Rule 16-1).',
        },
      },
      {
        title: 'The offseason: building a roster',
        ov: [{ id: 'cal', type: 'calendar', pos: 'c', hl: 1, foot: '**Hard salary cap** (same for all 32) · free agency in March · **7-round draft**: worst record picks first, Super Bowl winner last' }],
        tags: ['VERIFY: 2026 trade deadline date (Tue after Week 9?)', 'VERIFY: 53 active · 47–48 dress on game day · 16-man practice squad'],
        l3: { k: 'Offseason', t: 'Cap, free agency, draft', s: 'Every team works under the same spending limit' },
        notes: {
          p: ['Salary cap: every team has the same hard spending limit for player salaries. You can\'t buy a championship; you have to manage it.',
            'Free agency starts in March: players whose contracts ended can sign anywhere. That\'s when teams spend their cap room.',
            'The Draft in April: 7 rounds of college players. The worst teams pick first; the Super Bowl winner picks last. It\'s the league\'s built-in way to help bad teams get better.',
            'During the season teams can still trade players until the trade deadline in early November.',
            'Rosters: 53 players on the active roster, about 47–48 of them dress for each game, plus a practice squad of around 16.'],
          a: 'Fantasy football with a fixed budget: everyone has the same money, the smart managers win.',
          x: 'Draft order: the 18 non-playoff teams pick 1–18 in reverse standings order; playoff teams pick by the round they lost in; Super Bowl loser 31st, winner 32nd (plus compensatory picks at the end of rounds 3–7).',
        },
      },
    ],
  });
})(window.FD);
