/* Glossary terms: [term, definition, stepId] */
window.FD = window.FD || {};
FD.GLOSSARY = [
  ['AFC / NFC', 'The two conferences of 16 teams each. Their champions meet in the Super Bowl.', 'ch01-s02'],
  ['AFC East', 'The Patriots\' division: Bills, Dolphins, Patriots, Jets.', 'ch01-s03'],
  ['Audible', 'The quarterback changing the play at the line of scrimmage.', 'ch11-s08'],
  ['Automatic first down', 'A penalty result that gives the offense a new set of downs regardless of yardage (most defensive fouls).', 'ch13-s06'],
  ['Blitz', 'Sending extra rushers (linebackers or DBs) after the quarterback.', 'ch10-s10'],
  ['Bye week', 'The one week each season a team doesn\'t play.', 'ch16-s02'],
  ['Challenge', 'A coach throws a red flag to ask for a replay review of a call.', 'ch13-s14'],
  ['Chains', 'The 10-yard chain on the sideline that marks the line to gain.', 'ch07-s08'],
  ['Cornerback (CB)', 'Defensive back who covers the wide receivers.', 'ch06-s07'],
  ['Cover 1', 'Man coverage with one deep free safety.', 'ch10-s07'],
  ['Cover 2', 'Zone with two deep safeties splitting the field in halves.', 'ch10-s08'],
  ['Cover 3', 'Zone with three deep defenders, each taking a third.', 'ch10-s09'],
  ['Down', 'One play. The offense gets four downs to gain 10 yards.', 'ch05-s01'],
  ['Down & distance', 'The down number and yards to go, e.g. "3rd & 4".', 'ch05-s03'],
  ['Drive', 'A team\'s series of plays from when it gets the ball until it scores or gives it up.', 'ch05-s05'],
  ['End zone', 'The 10-yard area at each end where touchdowns are scored.', 'ch02-s02'],
  ['Extra point (PAT)', 'The 1-point kick try after a touchdown, snapped from the 15.', 'ch03-s03'],
  ['Fair catch', 'A returner waves one arm above his head: he can\'t be hit, but can\'t return the kick.', 'ch12-s09'],
  ['Field goal', 'A kick through the uprights from scrimmage: 3 points. Distance ≈ line of scrimmage + 17.', 'ch03-s05'],
  ['First down', 'Gaining the 10 yards: earns a new set of four downs.', 'ch05-s04'],
  ['Flag', 'The yellow penalty marker an official throws when a foul occurs.', 'ch13-s01'],
  ['Flex scheduling', 'Moving games into prime-time slots late in the season.', 'ch16-s10'],
  ['Fumble', 'A ball carrier losing the ball; either team can recover it.', 'ch14-s04'],
  ['Gap (A/B/C/D)', 'The spaces between offensive linemen that runs attack.', 'ch08-s02'],
  ['Hash marks', 'The two rows of lines in the middle of the field; each play starts on or between them.', 'ch02-s04'],
  ['Huddle', 'The offense gathering before a play to hear the call.', 'ch07-s01'],
  ['Interception', 'A defender catching a pass: turnover.', 'ch14-s01'],
  ['Landing zone', 'Kickoff area from the receiving 20 to the goal line where the kick must land.', 'ch12-s01'],
  ['Line of scrimmage', 'The blue line: where the ball is and each play starts.', 'ch05-s01'],
  ['Line to gain', 'The yellow line: the spot the offense must reach for a first down.', 'ch05-s01'],
  ['Linebacker (LB)', 'Second-level defender: stops runs, covers, blitzes.', 'ch06-s06'],
  ['Man coverage', 'Each defender follows one receiver.', 'ch10-s05'],
  ['MOFO / MOFC', 'Middle of the field open (two deep safeties) or closed (one deep safety).', 'ch11-s05'],
  ['Nickel', 'A defense with 5 defensive backs (the 5th is the nickel back).', 'ch10-s04'],
  ['Offensive line', 'The five blockers: tackles, guards, center.', 'ch06-s02'],
  ['Onside kick', 'A short kickoff the kicking team tries to recover. 2026: may be declared any time.', 'ch12-s07'],
  ['Overtime', 'Extra period when tied: 10 min in the regular season, 15-min periods in the playoffs.', 'ch04-s11'],
  ['Pass interference', 'Illegal contact that prevents a fair chance to catch a pass.', 'ch13-s07'],
  ['Personnel (11, 12…)', 'Offensive grouping: first digit = RBs, second = TEs.', 'ch06-s04'],
  ['Play-action', 'A fake handoff to freeze the defense before a pass.', 'ch11-s01'],
  ['Play clock', 'The 40-second (or 25) countdown to snap the ball.', 'ch04-s02'],
  ['Pocket', 'The protected area the offensive line forms around the QB.', 'ch09-s02'],
  ['Punt', 'A kick on 4th down to give the opponent worse field position.', 'ch12-s08'],
  ['Red zone', 'Inside the opponent\'s 20-yard line.', 'ch02-s07'],
  ['RPO', 'Run-pass option: the QB reads one defender to hand off or throw.', 'ch11-s03'],
  ['Route tree', 'The standard menu of receiver routes (slant, out, curl, post…).', 'ch09-s03'],
  ['Sack', 'Tackling the quarterback behind the line before he throws.', 'ch09-s08'],
  ['Safety (player)', 'Deep defensive back, last line of defense.', 'ch06-s07'],
  ['Safety (score)', 'Tackling the ball carrier in his own end zone: 2 points + the ball.', 'ch03-s06'],
  ['Score bug', 'The TV graphic with score, clock, down & distance.', 'ch17-s01'],
  ['Snap', 'The center passing the ball between his legs to start the play.', 'ch07-s04'],
  ['Special teams', 'The units on the field for kicking plays.', 'ch06-s08'],
  ['Touchback', 'Ball downed in the end zone after a kick/turnover: placed at the 20 (or 35 on some kickoffs).', 'ch12-s04'],
  ['Touchdown', 'Ball in possession crossing the goal line: 6 points.', 'ch03-s02'],
  ['Turnover on downs', 'Failing on 4th down: the other team takes over at that spot.', 'ch05-s08'],
  ['Two-minute warning', 'Automatic timeout at 2:00 left in each half.', 'ch04-s07'],
  ['Two-point try', 'A run or pass from the 2 after a touchdown: 2 points.', 'ch03-s04'],
  ['Victory formation', 'QB kneels to run out the clock when winning.', 'ch15-s07'],
  ['Wild card', 'Playoff team that didn\'t win its division (3 per conference).', 'ch16-s12'],
  ['Zone coverage', 'Defenders guard areas instead of specific receivers.', 'ch10-s06'],
];
